version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testjs
    networks:
      - testjs
  dev-redis:
    image: redis:alpine
    ports:
      - 6380:6379
    networks:
      - testjs
networks:
  testjs: